---
language: node_js
node_js:
- '0.10'
services:
- neo4j
before_script:
- npm install -g grunt-cli
addons:
  sauce_connect: true
deploy:
  provider: heroku
  app: agilejs-code-frantics
  strategy: git
  api_key:
    secure: ! 'LCqiUMgTM6Ejwjqrxu46QuGWKt706+CSpx9h5x6/FilSptLhAuIZP8pT8uZC

      QTAIw/IbT5Wb6hrUIux/cgwOpyE7Erof0G/9lYSFEXx+1npEJnO6iQPpS14c

      DLmvnBrNRgmu/UdxXRDKGyg51nRxIQx4NPDQNWKkB9ZSWsHDQi4='
env:
  global:
  - secure: bHg2qI7r+xRt+G7FLkKLf0qIentiFI2ZGSXW9hFCGMUSai8jPR8LYChHc2VhMhVXER1wurqnkOKfnuE9qE1/7cJ1pmtoU4x/ujdX6xOQnkPjCH01ZZNNAmWJMNpgmzUbwiYntIj1sqGYFLbPmSM3lECwF1dGjaiwX0Z9X/h8KYQ=
  - secure: HkyoqAMr63LkcKOMlUmnZ5Hbn0sKNVdEDbNWEY2rhQVkvg4fBFkCi3Xm20kf6qKgh7Md7iBIaklApiibAwmQtz/pMuWFtfd0K1UzRA63z03Ypn0NxLAwzjj6f4Gfu1WnYDrunHwOz2dGlPQvTOL2YOBXMYKff/24H6qnF55B/Cw=
